import ImageOutlinedIcon from "@mui/icons-material/ImageOutlined";
import Box from "@mui/material/Box";
import type { SxProps, Theme } from "@mui/material/styles";
import type { CardImage } from "@/services/catalog/types";

/** Rendition widths generated by the backend (config/media.php). */
const WIDTHS = { thumb: 200, sm: 400, md: 800, lg: 1600 } as const;

export function srcSetOf(image: Partial<Record<keyof typeof WIDTHS, string | null>>): string | undefined {
  // Before conversions finish every size points at the original; one entry is enough then.
  const entries = (Object.keys(WIDTHS) as (keyof typeof WIDTHS)[]).filter((k) => image[k]).map((k) => `${image[k]} ${WIDTHS[k]}w`);
  const unique = new Set((Object.keys(WIDTHS) as (keyof typeof WIDTHS)[]).map((k) => image[k]).filter(Boolean));
  return unique.size > 1 ? entries.join(", ") : undefined;
}

interface CatalogImageProps {
  image: CardImage | null | undefined;
  alt: string;
  /** CSS aspect ratio of the frame, e.g. "3 / 4". */
  ratio?: string;
  sizes?: string;
  priority?: boolean;
  sx?: SxProps<Theme>;
}

/**
 * Plain <img> with srcset: the backend already serves resized WebP renditions,
 * so no extra image optimizer is needed.
 */
export function CatalogImage({ image, alt, ratio = "3 / 4", sizes = "(max-width: 600px) 50vw, 25vw", priority, sx }: CatalogImageProps) {
  const src = image?.md ?? image?.sm ?? image?.lg ?? image?.thumb;

  return (
    <Box sx={{ position: "relative", aspectRatio: ratio, bgcolor: "action.hover", overflow: "hidden", ...sx }}>
      {src ? (
        <Box
          component="img"
          src={src}
          srcSet={image ? srcSetOf(image) : undefined}
          sizes={sizes}
          alt={image?.alt || alt}
          loading={priority ? "eager" : "lazy"}
          fetchPriority={priority ? "high" : undefined}
          decoding="async"
          sx={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover" }}
        />
      ) : (
        <Box sx={{ position: "absolute", inset: 0, display: "grid", placeItems: "center", color: "text.disabled" }}>
          <ImageOutlinedIcon fontSize="large" />
        </Box>
      )}
    </Box>
  );
}
